import {
  FishingHook, Lock, Database, Waves, Eye, Code2, Target, Drama, Globe, Package, UserX, BrainCircuit,
  Search, Mail, TriangleAlert, Monitor, Key, Skull, LogIn, Bug, Network, Upload,
  LockOpen, Coins, Bot, Cpu, Radio, Rocket, Zap, BarChart2, Terminal, Building2,
  Syringe, Moon, ScanEye, UserMinus, Smartphone, Wind, Eraser, Shuffle, Cookie, Pencil,
  User, Microscope, Settings2, Bomb, VolumeX, Biohazard, Clock, Save, CircuitBoard,
  Flame, LockKeyhole, HardDrive,
  KeyRound, Ghost, MousePointerClick, RefreshCw, Activity, PhoneCall, PhoneForwarded,
  Wrench, Usb, Rainbow, Hammer, CloudOff, ArrowLeftRight, TabletSmartphone,
  type LucideIcon,
} from 'lucide-react';

export const ATTACK_ICON_MAP: Record<string, LucideIcon> = {
  phishing: FishingHook,
  ransomware: Lock,
  sqli: Database,
  ddos: Waves,
  mitm: Eye,
  xss: Code2,
  'zero-day': Target,
  'social-engineering': Drama,
  'dns-spoofing': Globe,
  'supply-chain': Package,
  'insider-threat': UserX,
  'ai-attack': BrainCircuit,
  'credential-stuffing': KeyRound,
  'cryptojacking': Cpu,
  'csrf': RefreshCw,
  'sim-swapping': Smartphone,
  'fileless-malware': Ghost,
  'clickjacking': MousePointerClick,
  'evil-maid': Wrench,
  'bad-usb': Usb,
  'rainbow-table': Rainbow,
  'brute-force': Hammer,
  'cloud-misconfig': CloudOff,
  'ssrf': ArrowLeftRight,
  'mobile-malware': TabletSmartphone,
  'iot-botnet': Radio,
  'log4shell': Flame,
  'printnightmare': Settings2,
  'oauth-bypass': LockOpen,
  'ssti': Terminal,
  'xxe': Upload,
  'jwt-attack': Key,
  'subdomain-takeover': Globe,
  'arp-spoofing': Shuffle,
  'bec': Mail,
  'watering-hole': Search,
  'keylogger': Pencil,
  'rootkit': HardDrive,
  'tailgating': User,
  'qrishing': ScanEye,
  'dependency-confusion': Package,
};

export const STEP_ICON_MAP: Record<string, LucideIcon> = {
  '🔍': Search,
  '📧': Mail,
  '😰': TriangleAlert,
  '🖥️': Monitor,
  '🔑': Key,
  '💀': Skull,
  '🚪': LogIn,
  '🐛': Bug,
  '🕸️': Network,
  '📤': Upload,
  '🔐': LockKeyhole,
  '💸': Coins,
  '🤖': Bot,
  '👾': Cpu,
  '📡': Radio,
  '🚀': Rocket,
  '💥': Flame,
  '🔓': LockOpen,
  '📊': BarChart2,
  '💻': Terminal,
  '🏢': Building2,
  '💉': Syringe,
  '😴': Moon,
  '🕵️': ScanEye,
  '💰': Coins,
  '😤': UserMinus,
  '📱': Smartphone,
  '💨': Wind,
  '🧹': Eraser,
  '🔀': Shuffle,
  '🍪': Cookie,
  '✏️': Pencil,
  '🎭': Drama,
  '👤': User,
  '⚡': Zap,
  '🔬': Microscope,
  '⚙️': Settings2,
  '💣': Bomb,
  '🎯': Target,
  '🤫': VolumeX,
  '🦠': Biohazard,
  '⏰': Clock,
  '💾': HardDrive,
  '🔮': CircuitBoard,
};
